# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/QIdle/forms/settings_page_general.ui'
#
# Created: Mon Dec 15 22:43:59 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from pyqode.qt import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(714, 665)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QLabel(Form)
        self.header.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(161, 161, 161);\n"
"padding: 10px;")
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout.addWidget(self.header)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cb_reopen = QtWidgets.QCheckBox(self.groupBox)
        self.cb_reopen.setChecked(True)
        self.cb_reopen.setObjectName("cb_reopen")
        self.verticalLayout_3.addWidget(self.cb_reopen)
        self.cb_confirm_exit = QtWidgets.QCheckBox(self.groupBox)
        self.cb_confirm_exit.setChecked(True)
        self.cb_confirm_exit.setObjectName("cb_confirm_exit")
        self.verticalLayout_3.addWidget(self.cb_confirm_exit)
        self.cb_restore_prev_win_state = QtWidgets.QCheckBox(self.groupBox)
        self.cb_restore_prev_win_state.setChecked(False)
        self.cb_restore_prev_win_state.setObjectName("cb_restore_prev_win_state")
        self.verticalLayout_3.addWidget(self.cb_restore_prev_win_state)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rb_open_scr_in_new = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_open_scr_in_new.setChecked(True)
        self.rb_open_scr_in_new.setObjectName("rb_open_scr_in_new")
        self.verticalLayout_4.addWidget(self.rb_open_scr_in_new)
        self.rb_open_scr_in_same = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_open_scr_in_same.setChecked(False)
        self.rb_open_scr_in_same.setObjectName("rb_open_scr_in_same")
        self.verticalLayout_4.addWidget(self.rb_open_scr_in_same)
        self.rb_open_scr_ask = QtWidgets.QRadioButton(self.groupBox_2)
        self.rb_open_scr_ask.setObjectName("rb_open_scr_ask")
        self.verticalLayout_4.addWidget(self.rb_open_scr_ask)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rb_open_proj_in_new = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_open_proj_in_new.setChecked(True)
        self.rb_open_proj_in_new.setObjectName("rb_open_proj_in_new")
        self.verticalLayout_5.addWidget(self.rb_open_proj_in_new)
        self.rb_open_proj_in_same = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_open_proj_in_same.setObjectName("rb_open_proj_in_same")
        self.verticalLayout_5.addWidget(self.rb_open_proj_in_same)
        self.rb_open_proj_ask = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_open_proj_ask.setObjectName("rb_open_proj_ask")
        self.verticalLayout_5.addWidget(self.rb_open_proj_ask)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cb_save_before_run = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb_save_before_run.setChecked(True)
        self.cb_save_before_run.setObjectName("cb_save_before_run")
        self.verticalLayout_6.addWidget(self.cb_save_before_run)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.header.setText(_translate("Form", "Configure general settings"))
        self.groupBox.setTitle(_translate("Form", "Startup/Shutdown"))
        self.cb_reopen.setText(_translate("Form", "Reopen last window (project or script) on startup"))
        self.cb_confirm_exit.setText(_translate("Form", "Confirm application exit "))
        self.cb_restore_prev_win_state.setText(_translate("Form", "Restore state of previous window"))
        self.groupBox_2.setTitle(_translate("Form", "Script opening"))
        self.rb_open_scr_in_new.setText(_translate("Form", "Open script in a new window"))
        self.rb_open_scr_in_same.setText(_translate("Form", "Open script in the same window (replace current script)"))
        self.rb_open_scr_ask.setText(_translate("Form", "Ask each time"))
        self.groupBox_3.setTitle(_translate("Form", "Project opening"))
        self.rb_open_proj_in_new.setText(_translate("Form", "Open project in a new window"))
        self.rb_open_proj_in_same.setText(_translate("Form", "Open project in the same window (replace current project)"))
        self.rb_open_proj_ask.setText(_translate("Form", "Ask each time"))
        self.groupBox_4.setTitle(_translate("Form", "Save"))
        self.cb_save_before_run.setText(_translate("Form", "Save editors before run"))
