# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/renega_666/Documents/QIdle/forms/settings_page_editor.ui'
#
# Created: Fri Dec 12 22:06:45 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from pyqode.qt import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(466, 569)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QLabel(Form)
        self.header.setStyleSheet("border-radius: 3px;\n"
"background-color: rgb(161, 161, 161);\n"
"padding: 10px;")
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout.addWidget(self.header)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cb_spaces_instead_of_tabs = QtWidgets.QCheckBox(self.groupBox)
        self.cb_spaces_instead_of_tabs.setText("")
        self.cb_spaces_instead_of_tabs.setObjectName("cb_spaces_instead_of_tabs")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_spaces_instead_of_tabs)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cb_center_on_scoll = QtWidgets.QCheckBox(self.groupBox)
        self.cb_center_on_scoll.setText("")
        self.cb_center_on_scoll.setObjectName("cb_center_on_scoll")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cb_center_on_scoll)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sb_tab_len = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_tab_len.sizePolicy().hasHeightForWidth())
        self.sb_tab_len.setSizePolicy(sizePolicy)
        self.sb_tab_len.setProperty("value", 4)
        self.sb_tab_len.setObjectName("sb_tab_len")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sb_tab_len)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sb_margin_pos = QtWidgets.QSpinBox(self.groupBox)
        self.sb_margin_pos.setMaximum(200)
        self.sb_margin_pos.setProperty("value", 120)
        self.sb_margin_pos.setObjectName("sb_margin_pos")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_margin_pos)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cb_caret_cope = QtWidgets.QCheckBox(self.groupBox)
        self.cb_caret_cope.setText("")
        self.cb_caret_cope.setObjectName("cb_caret_cope")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cb_caret_cope)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cb_convert_tabs_to_spaces = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_convert_tabs_to_spaces.setObjectName("cb_convert_tabs_to_spaces")
        self.verticalLayout_3.addWidget(self.cb_convert_tabs_to_spaces)
        self.cb_clean_trailing = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_clean_trailing.setObjectName("cb_clean_trailing")
        self.verticalLayout_3.addWidget(self.cb_clean_trailing)
        self.cb_restore_cursor = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_restore_cursor.setObjectName("cb_restore_cursor")
        self.verticalLayout_3.addWidget(self.cb_restore_cursor)
        self.cb_safe_save = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_safe_save.setObjectName("cb_safe_save")
        self.verticalLayout_3.addWidget(self.cb_safe_save)
        self.cb_fold_imports = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_fold_imports.setObjectName("cb_fold_imports")
        self.verticalLayout_3.addWidget(self.cb_fold_imports)
        self.cb_fold_doc = QtWidgets.QCheckBox(self.groupBox_3)
        self.cb_fold_doc.setObjectName("cb_fold_doc")
        self.verticalLayout_3.addWidget(self.cb_fold_doc)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sb_cc_trigger_len = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_cc_trigger_len.sizePolicy().hasHeightForWidth())
        self.sb_cc_trigger_len.setSizePolicy(sizePolicy)
        self.sb_cc_trigger_len.setObjectName("sb_cc_trigger_len")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sb_cc_trigger_len)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cb_cc_tooltips = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_cc_tooltips.setText("")
        self.cb_cc_tooltips.setObjectName("cb_cc_tooltips")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_cc_tooltips)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cb_cc_case_sensitive = QtWidgets.QCheckBox(self.groupBox_2)
        self.cb_cc_case_sensitive.setText("")
        self.cb_cc_case_sensitive.setObjectName("cb_cc_case_sensitive")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_cc_case_sensitive)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.header.setText(_translate("Form", "Configure editor settings"))
        self.groupBox.setTitle(_translate("Form", "General"))
        self.label_5.setText(_translate("Form", "Use spaces instead of tabs:"))
        self.label_8.setText(_translate("Form", "Center on scroll"))
        self.label.setText(_translate("Form", "Tab length (nb spaces):"))
        self.label_2.setText(_translate("Form", "Margin position:"))
        self.label_4.setText(_translate("Form", "Highlight caret scope:"))
        self.groupBox_3.setTitle(_translate("Form", "Open/Save"))
        self.cb_convert_tabs_to_spaces.setText(_translate("Form", "Convert tabs to spaces"))
        self.cb_clean_trailing.setText(_translate("Form", "Clean trailing white-spaces"))
        self.cb_restore_cursor.setText(_translate("Form", "Restore cursor position"))
        self.cb_safe_save.setText(_translate("Form", "Safe save (save to a temporary file first)"))
        self.cb_fold_imports.setText(_translate("Form", "Fold imports"))
        self.cb_fold_doc.setText(_translate("Form", "Fold docstrings"))
        self.groupBox_2.setTitle(_translate("Form", "Code completion"))
        self.label_3.setText(_translate("Form", "Trigger length:"))
        self.label_6.setText(_translate("Form", "Show tooltips:"))
        self.label_7.setText(_translate("Form", "Case sensitive:"))
