# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/dev/QIdle/forms/widget_run_cfg.ui'
#
# Created: Wed Nov 26 13:26:40 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from pyqode.qt import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(558, 381)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.pickerScript = FilePicker(Form)
        self.pickerScript.setObjectName("pickerScript")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pickerScript)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditScriptParams = QtWidgets.QLineEdit(Form)
        self.lineEditScriptParams.setObjectName("lineEditScriptParams")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditScriptParams)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBoxInterpreter = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxInterpreter.sizePolicy().hasHeightForWidth())
        self.comboBoxInterpreter.setSizePolicy(sizePolicy)
        self.comboBoxInterpreter.setObjectName("comboBoxInterpreter")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxInterpreter)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdidInterpreterOpts = QtWidgets.QLineEdit(Form)
        self.lineEdidInterpreterOpts.setObjectName("lineEdidInterpreterOpts")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdidInterpreterOpts)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pickerWorkingDir = FilePicker(Form)
        self.pickerWorkingDir.setObjectName("pickerWorkingDir")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pickerWorkingDir)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidgetEnvVars = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidgetEnvVars.sizePolicy().hasHeightForWidth())
        self.tableWidgetEnvVars.setSizePolicy(sizePolicy)
        self.tableWidgetEnvVars.setAlternatingRowColors(False)
        self.tableWidgetEnvVars.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetEnvVars.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetEnvVars.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidgetEnvVars.setRowCount(0)
        self.tableWidgetEnvVars.setObjectName("tableWidgetEnvVars")
        self.tableWidgetEnvVars.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEnvVars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEnvVars.setHorizontalHeaderItem(1, item)
        self.tableWidgetEnvVars.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetEnvVars.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetEnvVars.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidgetEnvVars)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButtonAdd = QtWidgets.QToolButton(Form)
        self.toolButtonAdd.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.toolButtonAdd.setIcon(icon)
        self.toolButtonAdd.setObjectName("toolButtonAdd")
        self.verticalLayout.addWidget(self.toolButtonAdd)
        self.toolButtonRemove = QtWidgets.QToolButton(Form)
        self.toolButtonRemove.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.toolButtonRemove.setIcon(icon)
        self.toolButtonRemove.setObjectName("toolButtonRemove")
        self.verticalLayout.addWidget(self.toolButtonRemove)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Script:"))
        self.label_2.setText(_translate("Form", "Script parameters:"))
        self.label_3.setText(_translate("Form", "Interpreter:"))
        self.label_4.setText(_translate("Form", "Interpreter options:"))
        self.label_5.setText(_translate("Form", "Working directory:"))
        self.label_6.setText(_translate("Form", "Environment variables"))
        item = self.tableWidgetEnvVars.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidgetEnvVars.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Value"))

from qidle.widgets.picker import FilePicker